version: "3.8"

services:
  app:
    ports:
      - "80:80"
    container_name: neomorphic-metal-bands-prod
    image: neomorphic-metal-bands-prod
    build:
      context: .
      target: production
